version: '3.8'
services:
  sinatra-service:
    build:
      context: .
      dockerfile: Dockerfile.sinatra
    ports:
      - "4567:4567"
    networks:
      - my-network

  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - sinatra-service
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
